services:
  mcu-countdown:
    container_name: mcu-countdown
    image: diljotsg301/mcu-countdown:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      TMDB_API_KEY: "${TMDB_API_KEY}"
